[phases.setup]
nixPkgs = ["php83", "php83Extensions.pdo", "php83Extensions.pdo_pgsql", "php83Extensions.pgsql"]

[phases.install]
cmds = ["mkdir -p /app"]

[start]
cmd = "php -S 0.0.0.0:${PORT:-8080} -t ."
